/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from 'three'

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb")

  const screensRef = useRef()

  const matcapTexture = useTexture('/images/textures/mat1.webp')
  const windowTexture = useTexture('/images/textures/window.webp')
  const mousePadTexture = useTexture('/images/textures/mousepad.webp')


  const bodyMaterial = new THREE.MeshStandardMaterial({
    map: matcapTexture
  })
  const windowMaterial = new THREE.MeshStandardMaterial({
    map: windowTexture
  })
  const mousePadMaterial = new THREE.MeshStandardMaterial({
    map: mousePadTexture
  })
  const tableMaterial = new THREE.MeshStandardMaterial({
    color: 0xC49A6C
  })
  const curtainMaterial = new THREE.MeshStandardMaterial({
    color: 0xD90426
  })

  const radiatorMaterial = new THREE.MeshPhongMaterial({
    color: 0xffffff,
  });

  const compMaterial = new THREE.MeshStandardMaterial({
    color: 0x343a40,
  });
  const triangleMaterial = new THREE.MeshStandardMaterial({
    color: 0xffffff,
  });

  const pillowMaterial = new THREE.MeshPhongMaterial({
    color: 0xFAF9F6,
  });
  const handleMaterial = new THREE.MeshPhongMaterial({
    color: 0xD4AF37,
  });

  const chairMaterial = new THREE.MeshPhongMaterial({
    color: 0x000000,
  });


  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1.5}
          luminanceThreshold={0.2}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      <mesh geometry={nodes._________6_blinn1_0.geometry} material={curtainMaterial} />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={bodyMaterial} />
      <mesh geometry={nodes.cabin_blinn1_0.geometry} material={tableMaterial} />
      <mesh geometry={nodes.chair_body_blinn1_0.geometry} material={chairMaterial} />
      <mesh geometry={nodes.comp_blinn1_0.geometry} material={compMaterial} />
      <mesh ref={screensRef} geometry={nodes.emis_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.handls_blinn1_0.geometry} material={handleMaterial} />
      <mesh geometry={nodes.keyboard_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.kovrik_blinn1_0.geometry} material={mousePadMaterial} />
      <mesh geometry={nodes.lamp_bl_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.lamp_white_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.miuse_blinn1_0.geometry} material={mousePadMaterial} />
      <mesh geometry={nodes.monitor2_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.monitor3_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCylinder5_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pillows_blinn1_0.geometry} material={pillowMaterial} />
      <mesh geometry={nodes.polySurface53_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.radiator_blinn1_0.geometry} material={radiatorMaterial} />
      <mesh geometry={nodes.radiator_blinn1_0001.geometry} material={radiatorMaterial} />
      <mesh geometry={nodes.railing_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.red_bttns_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.red_vac_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.stylus_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={tableMaterial} />
      <mesh geometry={nodes.tablet_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.triangle_blinn1_0.geometry} material={triangleMaterial} />
      <mesh geometry={nodes.vac_black_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.vacuum1_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.vacuumgrey_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.vires_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.window_blinn1_0.geometry} material={windowMaterial} />
      <mesh geometry={nodes.window4_phong1_0.geometry} material={materials.phong1} />
    </group>
  )
}

useGLTF.preload("/models/optimized-room.glb")
